use std::{env, fs, path::PathBuf};

const ROM_BANKS: usize = 2;
const WORDS_PER_BANK: usize = 4096;
const WORDS_PER_PAGE: usize = 1024;
const ROM_PAGES: usize = 4;
const PHYSICAL_ROM_WORDS: usize = ROM_BANKS * WORDS_PER_BANK;
const EXPECTED_POPULATED_WORDS: usize = 5120;
const MISSING_WORD: u16 = 0xffff;

fn main() {
    println!("cargo:rerun-if-env-changed=HP67_ROM_CORPUS_BUILD");

    let manifest_dir = PathBuf::from(env::var_os("CARGO_MANIFEST_DIR").expect("CARGO_MANIFEST_DIR"));
    let corpus_path = env::var_os("HP67_ROM_CORPUS_BUILD")
        .map(PathBuf::from)
        .unwrap_or_else(|| manifest_dir.join(".research/teenix-2026-hp67.tsv"));
    println!("cargo:rerun-if-changed={}", corpus_path.display());

    let input = fs::read_to_string(&corpus_path).unwrap_or_else(|error| {
        panic!(
            "HP-67 build corpus is required only while compiling, not at runtime. Missing {}: {error}. Run docs/research/bootstrap_teenix_hp67.ps1 first, or set HP67_ROM_CORPUS_BUILD.",
            corpus_path.display()
        )
    });

    let (words, page_bank_mask, populated) = parse_corpus(&input);
    assert_eq!(
        populated, EXPECTED_POPULATED_WORDS,
        "HP-67 corpus contains {populated} populated words; expected {EXPECTED_POPULATED_WORDS}"
    );
    assert_eq!(words[0], 0x000, "HP-67 reset vector mismatch");
    assert_eq!(words[1], 0x3e3, "HP-67 startup word 1 mismatch");
    assert_eq!(words[0x0f8], 0x11a, "HP-67 startup word 0x0f8 mismatch");

    let out_dir = PathBuf::from(env::var_os("OUT_DIR").expect("OUT_DIR"));
    let generated = out_dir.join("hp67_embedded_rom.rs");
    let mut source = String::new();
    source.push_str("// @generated by build.rs from the locally validated HP-67 ROM corpus.\n");
    source.push_str(&format!(
        "pub(super) const EMBEDDED_HP67_POPULATED_WORDS: usize = {populated};\n"
    ));
    source.push_str("pub(super) const EMBEDDED_HP67_PAGE_BANK_MASK: [u8; 4] = [");
    for (index, mask) in page_bank_mask.iter().enumerate() {
        if index != 0 {
            source.push_str(", ");
        }
        source.push_str(&format!("0x{mask:02x}"));
    }
    source.push_str("];\n");
    source.push_str("pub(super) const EMBEDDED_HP67_WORDS: [u16; 8192] = [\n");
    for chunk in words.chunks(16) {
        source.push_str("    ");
        for word in chunk {
            source.push_str(&format!("0x{word:04x}, "));
        }
        source.push('\n');
    }
    source.push_str("];\n");
    fs::write(&generated, source)
        .unwrap_or_else(|error| panic!("failed to write {}: {error}", generated.display()));
}

fn parse_corpus(input: &str) -> ([u16; PHYSICAL_ROM_WORDS], [u8; ROM_PAGES], usize) {
    let mut words = [MISSING_WORD; PHYSICAL_ROM_WORDS];
    let mut page_bank_mask = [0u8; ROM_PAGES];
    let mut populated = 0usize;

    for (line_index, raw_line) in input.lines().enumerate() {
        let line = raw_line.trim();
        if line.is_empty() || line.starts_with('#') || line.eq_ignore_ascii_case("bank\tpc\tword") {
            continue;
        }
        let fields: Vec<_> = line.split_whitespace().collect();
        assert_eq!(
            fields.len(), 3,
            "invalid HP-67 corpus line {}: {raw_line}",
            line_index + 1
        );
        let bank = parse_integer(fields[0]) as usize;
        let pc = parse_integer(fields[1]) as usize;
        let word = parse_integer(fields[2]);
        assert!(bank < ROM_BANKS, "ROM bank out of range on line {}", line_index + 1);
        assert!(pc < WORDS_PER_BANK, "ROM PC out of range on line {}", line_index + 1);
        assert!(word <= 0x03ff, "ROM word out of range on line {}", line_index + 1);

        let flat = bank * WORDS_PER_BANK + pc;
        assert_eq!(
            words[flat], MISSING_WORD,
            "duplicate HP-67 ROM location bank {bank}, pc 0x{pc:03x}"
        );
        words[flat] = word;
        page_bank_mask[pc / WORDS_PER_PAGE] |= 1u8 << bank;
        populated += 1;
    }

    (words, page_bank_mask, populated)
}

fn parse_integer(token: &str) -> u16 {
    let trimmed = token.trim();
    if let Some(rest) = trimmed
        .strip_prefix("0x")
        .or_else(|| trimmed.strip_prefix("0X"))
    {
        u16::from_str_radix(rest, 16).unwrap_or_else(|_| panic!("invalid hexadecimal ROM value {token}"))
    } else if let Some(rest) = trimmed
        .strip_prefix("0o")
        .or_else(|| trimmed.strip_prefix("0O"))
    {
        u16::from_str_radix(rest, 8).unwrap_or_else(|_| panic!("invalid octal ROM value {token}"))
    } else {
        trimmed
            .parse::<u16>()
            .unwrap_or_else(|_| panic!("invalid decimal ROM value {token}"))
    }
}
