[package]
name = "hp67emu"
version = "0.1.0"
edition = "2021"
rust-version = "1.76"
description = "Photorealistic HP-67 emulator front panel in Rust"
repository = "https://github.com/TheWinterLynx/hp67emu"
publish = false
default-run = "hp67emu"

[dependencies]
eframe = { version = "=0.27.2", features = ["wgpu"] }
image = { version = "=0.24.9", default-features = false, features = ["png"] }
web-time = "=0.2.4"

[target.'cfg(target_arch = "wasm32")'.dependencies]
wasm-bindgen-futures = "=0.4.78"

[profile.release]
lto = "thin"
codegen-units = 1
strip = true
