//! Source-backed HP-67 keyboard contact matrix.
//!
//! The keyboard is deliberately modeled as physical contacts plus the scan
//! code seen by the ACT.  It does not perform calculator operations and it
//! never edits calculator registers other than the ACT key-buffer input.  The
//! scan codes below follow the HP-67 key matrix used by the preserved firmware
//! and independently documented emulator sources; values are written in octal
//! to match the historical listings.

use super::ActArchitecturalState;

#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub enum Hp67Key {
    A,
    B,
    C,
    D,
    E,
    SigmaPlus,
    Gto,
    Dsp,
    Indirect,
    Sst,
    FunctionF,
    FunctionG,
    Sto,
    Rcl,
    FunctionH,
    Enter,
    ChangeSign,
    Exponent,
    ClearX,
    Subtract,
    Digit7,
    Digit8,
    Digit9,
    Add,
    Digit4,
    Digit5,
    Digit6,
    Multiply,
    Digit1,
    Digit2,
    Digit3,
    Divide,
    Digit0,
    Decimal,
    RunStop,
}

impl Hp67Key {
    /// Return the six/eight-bit ACT keyboard scan code generated by the real
    /// HP-67 matrix.  Octal notation preserves the row/column pattern visible
    /// in the historical firmware and keyboard tables.
    pub const fn scan_code(self) -> u8 {
        match self {
            Self::A => 0o244,
            Self::B => 0o243,
            Self::C => 0o242,
            Self::D => 0o241,
            Self::E => 0o240,
            Self::SigmaPlus => 0o224,
            Self::Gto => 0o223,
            Self::Dsp => 0o222,
            Self::Indirect => 0o221,
            Self::Sst => 0o220,
            Self::FunctionF => 0o024,
            Self::FunctionG => 0o023,
            Self::Sto => 0o022,
            Self::Rcl => 0o021,
            Self::FunctionH => 0o020,
            Self::Enter => 0o063,
            Self::ChangeSign => 0o062,
            Self::Exponent => 0o061,
            Self::ClearX => 0o060,
            Self::Subtract => 0o103,
            Self::Digit7 => 0o102,
            Self::Digit8 => 0o101,
            Self::Digit9 => 0o100,
            Self::Add => 0o123,
            Self::Digit4 => 0o122,
            Self::Digit5 => 0o121,
            Self::Digit6 => 0o120,
            Self::Multiply => 0o143,
            Self::Digit1 => 0o142,
            Self::Digit2 => 0o141,
            Self::Digit3 => 0o140,
            Self::Divide => 0o163,
            Self::Digit0 => 0o162,
            Self::Decimal => 0o161,
            Self::RunStop => 0o160,
        }
    }
}

/// Physical keyboard contact state.
///
/// The first pass intentionally models one closed key contact at a time.  That
/// is sufficient for normal HP-67 operation and avoids inventing semantics for
/// impossible/undefined multi-key combinations.  Contact lifetime is owned by
/// the caller: press closes the contact, release opens it.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Default)]
pub struct Hp67Keyboard {
    pressed: Option<Hp67Key>,
}

impl Hp67Keyboard {
    pub const fn pressed(&self) -> Option<Hp67Key> {
        self.pressed
    }

    pub const fn scan_code(&self) -> Option<u8> {
        match self.pressed {
            Some(key) => Some(key.scan_code()),
            None => None,
        }
    }

    pub fn press(&mut self, key: Hp67Key) {
        self.pressed = Some(key);
    }

    pub fn release(&mut self) {
        self.pressed = None;
    }

    /// Instruction-boundary bridge used by the current ACT bring-up core.
    ///
    /// This is not a calculator-level key handler: it only presents the scan
    /// code generated by the closed keyboard contact to the ACT key input.  The
    /// HP-67 firmware remains solely responsible for dispatch and behavior.
    pub fn sample_into_act(&self, act: &mut ActArchitecturalState) {
        act.key_buffer = self.scan_code();
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use std::collections::HashSet;

    const ALL_KEYS: [Hp67Key; 35] = [
        Hp67Key::A,
        Hp67Key::B,
        Hp67Key::C,
        Hp67Key::D,
        Hp67Key::E,
        Hp67Key::SigmaPlus,
        Hp67Key::Gto,
        Hp67Key::Dsp,
        Hp67Key::Indirect,
        Hp67Key::Sst,
        Hp67Key::FunctionF,
        Hp67Key::FunctionG,
        Hp67Key::Sto,
        Hp67Key::Rcl,
        Hp67Key::FunctionH,
        Hp67Key::Enter,
        Hp67Key::ChangeSign,
        Hp67Key::Exponent,
        Hp67Key::ClearX,
        Hp67Key::Subtract,
        Hp67Key::Digit7,
        Hp67Key::Digit8,
        Hp67Key::Digit9,
        Hp67Key::Add,
        Hp67Key::Digit4,
        Hp67Key::Digit5,
        Hp67Key::Digit6,
        Hp67Key::Multiply,
        Hp67Key::Digit1,
        Hp67Key::Digit2,
        Hp67Key::Digit3,
        Hp67Key::Divide,
        Hp67Key::Digit0,
        Hp67Key::Decimal,
        Hp67Key::RunStop,
    ];

    #[test]
    fn hp67_matrix_contains_35_unique_scan_codes() {
        let codes: HashSet<_> = ALL_KEYS.into_iter().map(Hp67Key::scan_code).collect();
        assert_eq!(codes.len(), ALL_KEYS.len());
    }

    #[test]
    fn digit_one_contact_is_historical_octal_0142() {
        assert_eq!(Hp67Key::Digit1.scan_code(), 0o142);
        assert_eq!(Hp67Key::Digit1.scan_code(), 0x62);
    }

    #[test]
    fn closed_contact_only_drives_act_key_input() {
        let mut keyboard = Hp67Keyboard::default();
        let mut act = ActArchitecturalState::default();

        keyboard.press(Hp67Key::Digit1);
        keyboard.sample_into_act(&mut act);
        assert_eq!(act.key_buffer, Some(0o142));

        keyboard.release();
        keyboard.sample_into_act(&mut act);
        assert_eq!(act.key_buffer, None);
    }
}
