//! Measured design coordinates. See tools/visual_compare/measurements.json.
use crate::hp67::KeyAction;
use eframe::egui::{Pos2, Rect, Vec2};
pub(crate) const DESIGN_W: f32 = 330.0;
pub(crate) const DESIGN_H: f32 = 620.0;
#[derive(Clone, Copy)]
pub(crate) enum KeyStyle {
    Olive,
    Orange,
    Blue,
    White,
    Black,
}

#[derive(Clone, Copy)]
pub(crate) enum SubAlign {
    Center,
    Right,
}

#[derive(Clone, Copy)]
pub(crate) struct KeySpec {
    pub(crate) id: &'static str,
    pub(crate) cx: f32,
    pub(crate) y: f32,
    pub(crate) w: f32,
    pub(crate) h: f32,
    pub(crate) top_h: f32,
    pub(crate) style: KeyStyle,
    pub(crate) main: &'static str,
    pub(crate) sub: Option<&'static str>,
    pub(crate) sub_align: SubAlign,
    pub(crate) action: KeyAction,
}

const fn k(
    id: &'static str,
    cx: f32,
    y: f32,
    w: f32,
    h: f32,
    top_h: f32,
    style: KeyStyle,
    main: &'static str,
    sub: Option<&'static str>,
    sub_align: SubAlign,
    action: KeyAction,
) -> KeySpec {
    KeySpec {
        id,
        cx,
        y,
        w,
        h,
        top_h,
        style,
        main,
        sub,
        sub_align,
        action,
    }
}

pub(crate) const KEYS: &[KeySpec] = &[
    k(
        "a",
        58.0,
        169.0,
        35.0,
        29.5,
        20.0,
        KeyStyle::Olive,
        "A",
        None,
        SubAlign::Center,
        KeyAction::A,
    ),
    k(
        "b",
        112.0,
        169.0,
        35.0,
        29.5,
        20.0,
        KeyStyle::Olive,
        "B",
        None,
        SubAlign::Center,
        KeyAction::B,
    ),
    k(
        "c",
        166.0,
        169.0,
        35.0,
        29.5,
        20.0,
        KeyStyle::Olive,
        "C",
        None,
        SubAlign::Center,
        KeyAction::C,
    ),
    k(
        "d",
        220.0,
        169.0,
        35.0,
        29.5,
        20.0,
        KeyStyle::Olive,
        "D",
        None,
        SubAlign::Center,
        KeyAction::D,
    ),
    k(
        "e",
        274.0,
        169.0,
        35.0,
        29.5,
        20.0,
        KeyStyle::Olive,
        "E",
        None,
        SubAlign::Center,
        KeyAction::E,
    ),
    k(
        "sigma",
        58.0,
        223.0,
        35.0,
        29.0,
        21.0,
        KeyStyle::Olive,
        "",
        Some(""),
        SubAlign::Center,
        KeyAction::SigmaPlus,
    ),
    k(
        "gto",
        112.0,
        223.0,
        35.0,
        29.0,
        21.0,
        KeyStyle::Olive,
        "GTO",
        Some("RTN"),
        SubAlign::Center,
        KeyAction::Gto,
    ),
    k(
        "dsp",
        166.0,
        223.0,
        35.0,
        29.0,
        21.0,
        KeyStyle::Olive,
        "DSP",
        Some("ENG"),
        SubAlign::Center,
        KeyAction::Dsp,
    ),
    k(
        "indirect",
        220.0,
        223.0,
        35.0,
        29.0,
        21.0,
        KeyStyle::Olive,
        "(i)",
        Some(""),
        SubAlign::Center,
        KeyAction::Indirect,
    ),
    k(
        "sst",
        274.0,
        223.0,
        35.0,
        29.0,
        21.0,
        KeyStyle::Olive,
        "SST",
        Some("BST"),
        SubAlign::Center,
        KeyAction::Sst,
    ),
    k(
        "f",
        58.0,
        277.0,
        35.0,
        29.5,
        20.0,
        KeyStyle::Orange,
        "f",
        None,
        SubAlign::Center,
        KeyAction::FunctionF,
    ),
    k(
        "g",
        112.0,
        277.0,
        35.0,
        29.5,
        20.0,
        KeyStyle::Blue,
        "g",
        None,
        SubAlign::Center,
        KeyAction::FunctionG,
    ),
    k(
        "sto",
        166.0,
        277.0,
        35.0,
        29.0,
        21.0,
        KeyStyle::Olive,
        "STO",
        Some("ST I"),
        SubAlign::Center,
        KeyAction::Sto,
    ),
    k(
        "rcl",
        220.0,
        277.0,
        35.0,
        29.0,
        21.0,
        KeyStyle::Olive,
        "RCL",
        Some("RC I"),
        SubAlign::Center,
        KeyAction::Rcl,
    ),
    k(
        "h",
        274.0,
        277.0,
        35.0,
        29.5,
        20.0,
        KeyStyle::Black,
        "h",
        None,
        SubAlign::Center,
        KeyAction::FunctionH,
    ),
    k(
        "enter",
        87.0,
        331.0,
        84.0,
        29.0,
        21.0,
        KeyStyle::Olive,
        "ENTER",
        Some("DEG"),
        SubAlign::Right,
        KeyAction::Enter,
    ),
    k(
        "chs",
        166.0,
        331.0,
        35.0,
        29.0,
        21.0,
        KeyStyle::Olive,
        "CHS",
        Some("RAD"),
        SubAlign::Center,
        KeyAction::ChangeSign,
    ),
    k(
        "eex",
        220.0,
        331.0,
        35.0,
        29.0,
        21.0,
        KeyStyle::Olive,
        "EEX",
        Some("GRD"),
        SubAlign::Center,
        KeyAction::Enter,
    ),
    k(
        "clx",
        274.0,
        331.0,
        35.0,
        29.0,
        21.0,
        KeyStyle::Olive,
        "CLx",
        Some("DEL"),
        SubAlign::Center,
        KeyAction::ClearX,
    ),
    k(
        "minus",
        56.0,
        383.0,
        27.0,
        29.0,
        21.0,
        KeyStyle::Olive,
        "−",
        Some("SF"),
        SubAlign::Center,
        KeyAction::Subtract,
    ),
    k(
        "7",
        119.0,
        383.0,
        36.0,
        29.0,
        21.0,
        KeyStyle::White,
        "7",
        Some(""),
        SubAlign::Center,
        KeyAction::Digit(7),
    ),
    k(
        "8",
        194.0,
        383.0,
        36.0,
        29.0,
        21.0,
        KeyStyle::White,
        "8",
        Some(""),
        SubAlign::Center,
        KeyAction::Digit(8),
    ),
    k(
        "9",
        270.0,
        383.0,
        36.0,
        29.0,
        21.0,
        KeyStyle::White,
        "9",
        Some(""),
        SubAlign::Center,
        KeyAction::Digit(9),
    ),
    k(
        "plus",
        56.0,
        435.0,
        27.0,
        29.0,
        21.0,
        KeyStyle::Olive,
        "+",
        Some("CF"),
        SubAlign::Center,
        KeyAction::Add,
    ),
    k(
        "4",
        119.0,
        435.0,
        36.0,
        29.0,
        21.0,
        KeyStyle::White,
        "4",
        Some(""),
        SubAlign::Center,
        KeyAction::Digit(4),
    ),
    k(
        "5",
        194.0,
        435.0,
        36.0,
        29.0,
        21.0,
        KeyStyle::White,
        "5",
        Some(""),
        SubAlign::Center,
        KeyAction::Digit(5),
    ),
    k(
        "6",
        270.0,
        435.0,
        36.0,
        29.0,
        21.0,
        KeyStyle::White,
        "6",
        Some("ABS"),
        SubAlign::Center,
        KeyAction::Digit(6),
    ),
    k(
        "multiply",
        56.0,
        487.0,
        27.0,
        29.0,
        21.0,
        KeyStyle::Olive,
        "",
        Some("F?"),
        SubAlign::Center,
        KeyAction::Multiply,
    ),
    k(
        "1",
        119.0,
        487.0,
        36.0,
        29.0,
        21.0,
        KeyStyle::White,
        "1",
        Some("PAUSE"),
        SubAlign::Center,
        KeyAction::Digit(1),
    ),
    k(
        "2",
        194.0,
        487.0,
        36.0,
        29.0,
        21.0,
        KeyStyle::White,
        "2",
        Some(""),
        SubAlign::Center,
        KeyAction::Digit(2),
    ),
    k(
        "3",
        270.0,
        487.0,
        36.0,
        29.0,
        21.0,
        KeyStyle::White,
        "3",
        Some("REG"),
        SubAlign::Center,
        KeyAction::Digit(3),
    ),
    k(
        "divide",
        56.0,
        538.0,
        27.0,
        29.0,
        21.0,
        KeyStyle::Olive,
        "",
        Some("N!"),
        SubAlign::Center,
        KeyAction::Divide,
    ),
    k(
        "0",
        119.0,
        538.0,
        36.0,
        29.0,
        21.0,
        KeyStyle::White,
        "0",
        Some("LST x"),
        SubAlign::Center,
        KeyAction::Digit(0),
    ),
    k(
        "decimal",
        194.0,
        538.0,
        36.0,
        29.0,
        21.0,
        KeyStyle::White,
        ".",
        Some("H.MS+"),
        SubAlign::Center,
        KeyAction::Decimal,
    ),
    k(
        "rs",
        270.0,
        538.0,
        36.0,
        29.0,
        21.0,
        KeyStyle::White,
        "R/S",
        Some("SPACE"),
        SubAlign::Center,
        KeyAction::RunStop,
    ),
];

#[derive(Clone, Copy)]
pub(crate) struct Transform {
    pub(crate) origin: Pos2,
    pub(crate) scale: f32,
}
impl Transform {
    pub(crate) fn s(self, v: f32) -> f32 {
        v * self.scale
    }
    pub(crate) fn pos(self, x: f32, y: f32) -> Pos2 {
        Pos2::new(
            self.origin.x + x * self.scale,
            self.origin.y + y * self.scale,
        )
    }
    pub(crate) fn rect(self, x: f32, y: f32, w: f32, h: f32) -> Rect {
        Rect::from_min_size(self.pos(x, y), Vec2::new(self.s(w), self.s(h)))
    }
    pub(crate) fn translated_y(self, dy: f32) -> Self {
        Self {
            origin: Pos2::new(self.origin.x, self.origin.y + dy * self.scale),
            scale: self.scale,
        }
    }
}

pub(crate) fn scale_for(available: Vec2) -> f32 {
    if available.x <= 0.0 || available.y <= 0.0 {
        0.0
    } else {
        (available.x / DESIGN_W).min(available.y / DESIGN_H)
    }
}
